#!/bin/bash
  
echo "system update"
sudo dnf upgrade && sudo dnf autoremove && sudo dnf clean all
echo "python update"
python3 -mpip install --upgrade pip
python3 -mpip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 python3 -mpip install -U
